---
title: Kimi Hammerstroem
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
url: https://www.kimihammerstroem.com
description: London-based photographer
permalink: pretty
exclude:
- bower.json
- Gemfile.lock
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
email: info@kimihammerstroem.com
subscribe: 
analytics:
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
